[languages.en]
languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Josh Quinlan - British Audio Producer & Baritone"
copyright = "Â© Josh Quinlan"

[params]
  dateFormat = "2 January, 2006"
  mainSections = ["discography"]
  description = "British Audio Producer & Baritone"

[params.author]
  name = "Josh Quinlan"
  image = "img/author2.png"
  headline = "British Audio Producer & Baritone"
  bio = "British Audio Producer & Baritone"
  links = [
    { link = "https://joshquinlan.co.uk/" },
    { instagram = "https://instagram.com/JoshNQuinlan" },
    { email = "mailto:hello@joshquinlan.co.uk" },
  ]
