# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 20

[[main]]
  name = "Discography"
  pageRef = "discography"
  weight = 30

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 90

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[footer]]
  name = "Client Resources"
  pageRef = "clients"
  weight = 10

[[footer]]
  name = "Articles"
  pageRef = "posts"
  weight = 20
